In [80]:
import pandas as pd

In [84]:
df = pd.read_csv("raw/miplib_info.csv")

In [85]:
df

,InstanceInst.,StatusStat.,VariablesVari.,BinariesBina.,IntegersInte.,ContinuousCont.,ConstraintsCons.,Nonz.Nonz.,SubmitterSubm.,GroupGrou.,ObjectiveObje.,TagsTags.
0,10teams,easy,2025.0,1800.0,0.0,225,230,12150,MIPLIB submission pool,–,923.9999999999997,binary set_partitioning set_packing invariant_...
1,22433,easy,429.0,231.0,0.0,198,198,3408,MIPLIB submission pool,–,21477,mixed_binary general_linear
2,23588,easy,368.0,231.0,0.0,137,137,3701,MIPLIB submission pool,–,8089.999999999998,mixed_binary general_linear
3,2club200v15p5scn,hard,200.0,200.0,0.0,0,17013,104811,Balabhaskar Balasundaram,–,-70,binary variable_bound invariant_knapsack
4,30_70_45_05_100,easy,10772.0,10771.0,0.0,1,12050,45889,J. Walser,30_70,9,binary decomposition benchmark_suitable preced...
...,...,...,...,...,...,...,...,...,...,...,...,...
1060,woodlands09,hard,382147.0,382119.0,28.0,0,194599,2646003,George Fonseca,timetabling,0,aggregations variable_bound set_partitioning s...
1061,xmas10,open,8100.0,900.0,0.0,7200,9080,43635,Simon Felix,–,-497.0*,aggregations variable_bound cardinality invari...
1062,xmas10-2,open,8100.0,900.0,0.0,7200,8184,35561,Simon Felix,–,-497*,aggregations variable_bound cardinality invari...
1063,z26,open,17937.0,17937.0,0.0,0,850513,1715613,Daniel Bienstock,–,-1195.0*,binary variable_bound set_packing
1064,zeil,open,70116.0,5314.0,0.0,64802,81558,1628941,Andreas Bärmann,–,1086.261999999988*,precedence variable_bound mixed_binary

In [86]:
alex = pd.read_csv("raw/alexinstances.csv", sep=";")

In [87]:
alex["Name"]

0               10teams
1                 23588
2               30n20b8
3                50v-10
4                a1c1s1
             ...
327                umts
328    usAbbrv-8-25\_70
329                vpm1
330                vpm2
331           zib54-UUE
Name: Name, Length: 332, dtype: object

In [88]:
name = alex[["Name"]]

In [89]:
name

                 Name
0             10teams
1               23588
2             30n20b8
3              50v-10
4              a1c1s1
..                ...
327              umts
328  usAbbrv-8-25\_70
329              vpm1
330              vpm2
331         zib54-UUE

[332 rows x 1 columns]

In [90]:
name["Name"] = name["Name"].str.replace(r'\\_', '_', regex=True)

/var/folders/bs/06hvsvyd3tg0tg3r8dnfx4dm0000gn/T/ipykernel_77909/4149161653.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  name["Name"] = name["Name"].str.replace(r'\\_', '_', regex=True)

In [91]:
name

                Name
0            10teams
1              23588
2            30n20b8
3             50v-10
4             a1c1s1
..               ...
327             umts
328  usAbbrv-8-25_70
329             vpm1
330             vpm2
331        zib54-UUE

[332 rows x 1 columns]

In [92]:
df = df.rename(columns={'InstanceInst.':'Name'})

In [93]:
df

,Name,StatusStat.,VariablesVari.,BinariesBina.,IntegersInte.,ContinuousCont.,ConstraintsCons.,Nonz.Nonz.,SubmitterSubm.,GroupGrou.,ObjectiveObje.,TagsTags.
0,10teams,easy,2025.0,1800.0,0.0,225,230,12150,MIPLIB submission pool,–,923.9999999999997,binary set_partitioning set_packing invariant_...
1,22433,easy,429.0,231.0,0.0,198,198,3408,MIPLIB submission pool,–,21477,mixed_binary general_linear
2,23588,easy,368.0,231.0,0.0,137,137,3701,MIPLIB submission pool,–,8089.999999999998,mixed_binary general_linear
3,2club200v15p5scn,hard,200.0,200.0,0.0,0,17013,104811,Balabhaskar Balasundaram,–,-70,binary variable_bound invariant_knapsack
4,30_70_45_05_100,easy,10772.0,10771.0,0.0,1,12050,45889,J. Walser,30_70,9,binary decomposition benchmark_suitable preced...
...,...,...,...,...,...,...,...,...,...,...,...,...
1060,woodlands09,hard,382147.0,382119.0,28.0,0,194599,2646003,George Fonseca,timetabling,0,aggregations variable_bound set_partitioning s...
1061,xmas10,open,8100.0,900.0,0.0,7200,9080,43635,Simon Felix,–,-497.0*,aggregations variable_bound cardinality invari...
1062,xmas10-2,open,8100.0,900.0,0.0,7200,8184,35561,Simon Felix,–,-497*,aggregations variable_bound cardinality invari...
1063,z26,open,17937.0,17937.0,0.0,0,850513,1715613,Daniel Bienstock,–,-1195.0*,binary variable_bound set_packing
1064,zeil,open,70116.0,5314.0,0.0,64802,81558,1628941,Andreas Bärmann,–,1086.261999999988*,precedence variable_bound mixed_binary

In [94]:
new = name.merge(df, on='Name', how='inner')

In [95]:
new

,Name,StatusStat.,VariablesVari.,BinariesBina.,IntegersInte.,ContinuousCont.,ConstraintsCons.,Nonz.Nonz.,SubmitterSubm.,GroupGrou.,ObjectiveObje.,TagsTags.
0,10teams,easy,2025.0,1800.0,0.0,225,230,12150,MIPLIB submission pool,–,923.9999999999997,binary set_partitioning set_packing invariant_...
1,23588,easy,368.0,231.0,0.0,137,137,3701,MIPLIB submission pool,–,8089.999999999998,mixed_binary general_linear
2,30n20b8,easy,18380.0,18318.0,62.0,0,576,109706,"E. Coughlan, M. Lübbecke, J. Schulz",–,302,benchmark benchmark_suitable precedence set_pa...
3,50v-10,easy,2013.0,1464.0,183.0,366,233,2745,Serge Bisaillon,–,3311.1799841,benchmark decomposition benchmark_suitable mix...
4,a1c1s1,easy,3648.0,192.0,0.0,3456,3312,10178,"M. Vyve, Y. Pochet",c1s1,11503.444125,benchmark_suitable aggregations variable_bound...
...,...,...,...,...,...,...,...,...,...,...,...,...
210,tr12-30,easy,1080.0,360.0,0.0,720,750,2508,MIPLIB submission pool,–,130595.9999999999,benchmark decomposition benchmark_suitable agg...
211,traininstance6,easy,10218.0,4154.0,2056.0,4008,12309,32785,Gleb Belov,traininstance,28290,benchmark benchmark_suitable aggregations prec...
212,uct-subprob,easy,2256.0,379.0,0.0,1877,1973,10147,Gerald Lach,–,314,benchmark benchmark_suitable aggregations vari...
213,umts,easy,2947.0,2802.0,72.0,73,4465,22872,C. Polo,–,30090327.99999997,decomposition benchmark_suitable aggregations ...
214,usAbbrv-8-25_70,hard,2312.0,1681.0,0.0,631,3291,9628,publicly available,–,120,precedence invariant_knapsack knapsack mixed_b...

In [96]:
new.columns

Index(['Name', 'StatusStat.', 'VariablesVari.', 'BinariesBina.',
       'IntegersInte.', 'ContinuousCont.', 'ConstraintsCons.', 'Nonz.Nonz.',
       'SubmitterSubm.', 'GroupGrou.', 'ObjectiveObje.', 'TagsTags.'],
      dtype='object')

In [97]:
new = new[['Name', 'StatusStat.', 'VariablesVari.', 'BinariesBina.',
       'IntegersInte.', 'ContinuousCont.', 'ConstraintsCons.', 'Nonz.Nonz.', 'ObjectiveObje.']]

In [98]:
new

,Name,StatusStat.,VariablesVari.,BinariesBina.,IntegersInte.,ContinuousCont.,ConstraintsCons.,Nonz.Nonz.,ObjectiveObje.
0,10teams,easy,2025.0,1800.0,0.0,225,230,12150,923.9999999999997
1,23588,easy,368.0,231.0,0.0,137,137,3701,8089.999999999998
2,30n20b8,easy,18380.0,18318.0,62.0,0,576,109706,302
3,50v-10,easy,2013.0,1464.0,183.0,366,233,2745,3311.1799841
4,a1c1s1,easy,3648.0,192.0,0.0,3456,3312,10178,11503.444125
...,...,...,...,...,...,...,...,...,...
210,tr12-30,easy,1080.0,360.0,0.0,720,750,2508,130595.9999999999
211,traininstance6,easy,10218.0,4154.0,2056.0,4008,12309,32785,28290
212,uct-subprob,easy,2256.0,379.0,0.0,1877,1973,10147,314
213,umts,easy,2947.0,2802.0,72.0,73,4465,22872,30090327.99999997
214,usAbbrv-8-25_70,hard,2312.0,1681.0,0.0,631,3291,9628,120

In [100]:
mittelmann = pd.read_csv("raw/miplib_mittelmann.csv")

In [101]:
mittelmann

,Name,Dual Bound,Primal Bound,Gap%,Nodes,Time,Status,Solution
0,30n20b8,3.020000e+02,3.020000e+02,0.0,2053,150,ok,ok
1,50v-10,3.268506e+03,3.313180e+03,1.4,1104554,7201,stopped,ok
2,academictimetablesmall,8.881784e-16,1.000000e+20,--,1663,7200,stopped,--
3,air05,2.637400e+04,2.637400e+04,0.0,265,22,ok,ok
4,app1-1,-3.000000e+00,-3.000000e+00,0.0,2,3,ok,ok
...,...,...,...,...,...,...,...,...
235,uccase9,1.087540e+04,1.137114e+04,4.6,1144,7201,stopped,ok
236,uct-subprob,3.140000e+02,3.140000e+02,0.0,47598,1227,ok,ok
237,unitcal_7,1.963556e+07,1.963556e+07,0.0,444,364,ok,ok
238,var-smallemery-m6j6,-1.493750e+02,-1.493750e+02,0.0,755153,4090,ok,ok
239,wachplan,-8.000000e+00,-8.000000e+00,0.0,303150,2174,ok,ok

In [102]:
new = new.merge(mittelmann, on='Name', how='right')

In [103]:
new

,Name,StatusStat.,VariablesVari.,BinariesBina.,IntegersInte.,ContinuousCont.,ConstraintsCons.,Nonz.Nonz.,ObjectiveObje.,Dual Bound,Primal Bound,Gap%,Nodes,Time,Status,Solution
0,30n20b8,easy,18380.0,18318.0,62.0,0.0,576.0,109706.0,302,3.020000e+02,3.020000e+02,0.0,2053,150,ok,ok
1,50v-10,easy,2013.0,1464.0,183.0,366.0,233.0,2745.0,3311.1799841,3.268506e+03,3.313180e+03,1.4,1104554,7201,stopped,ok
2,academictimetablesmall,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.881784e-16,1.000000e+20,--,1663,7200,stopped,--
3,air05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.637400e+04,2.637400e+04,0.0,265,22,ok,ok
4,app1-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.000000e+00,-3.000000e+00,0.0,2,3,ok,ok
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,uccase9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.087540e+04,1.137114e+04,4.6,1144,7201,stopped,ok
236,uct-subprob,easy,2256.0,379.0,0.0,1877.0,1973.0,10147.0,314,3.140000e+02,3.140000e+02,0.0,47598,1227,ok,ok
237,unitcal_7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.963556e+07,1.963556e+07,0.0,444,364,ok,ok
238,var-smallemery-m6j6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.493750e+02,-1.493750e+02,0.0,755153,4090,ok,ok
239,wachplan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-8.000000e+00,-8.000000e+00,0.0,303150,2174,ok,ok

In [104]:
new.to_csv('miplib_full.csv', index=False)